name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: windows
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Yay! This is my first issue"
        pr-message: "Look mom, i did it"
